### ISSUE TITLE
not able to download large dataset

### ISSUE THREAD

**Issue by TaqwaGuy** [720922/chaosDump#1]
Hi,
thanks for the tool. As I was poking around the tool, I got some errors when I was trying to download verizon media dataset on my MacOs. The error below;

 Select the program from the databse...jq: error: Media/0 is not defined at <top-level>, line 1:
Media
jq: 1 compile error
[✔]/usr/local/bin/chaosdump: line 109: [: Verizon: binary operator expected

[+] Dumping data for Verizon Media...[✔]
[+] Extracting data...[Verizon]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Verizon or
        Verizon.zip, and cannot find Verizon.ZIP, period.
[✔]
[+] Dumped Data saved to folder rm: Media.zip: No such file or directory.

(2) And I want to suggest, if you could write a wrapper for alert on selected new discovered subdomains like "Anew" and "notify"

thanks

**Comment by jakre1234** [comment]
Hey @TaqwaGuy ,
Thanks for raising the issue, let me have a look into this one. Sorry for the delayed response, was going through a tight schedule. Also will add the said alert feature for newly added subdomains notification.

**Comment by rynosec** [comment]
Hey @TaqwaGuy ,
Thanks for raising the issue,had a quick look and now the issue seems to be resolved. Sorry for the delayed response, was going through a tight schedule.
